spring:
  datasource:
    url: jdbc:mysql://47.240.18.1/plane_reservation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: plane
    password: ooad4.0!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

dev:
  url: http://dev.bar.com
  name: Developer Setup

mybatis:
  configuration:
    map-underscore-to-camel-case: true